### ISSUE TITLE
Requirements are MS Windows-specific

### ISSUE THREAD

**Issue by stvhwrd** [pcinat/QuestradeAPI_PythonWrapper#2]
When I issue command `pip install -r requirements.txt` on macOS and Linux 16.04 I receive the following error:

```shell
Collecting pypiwin32==219 (from -r requirements.txt (line 42))
  Using cached pypiwin32-219.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/tl/y1b6r4xj4sd3g3bh2hzk52r80000gn/T/pip-build-GZzOww/pypiwin32/setup.py", line 83, in <module>
        import _winreg
    ImportError: No module named _winreg

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in 
/private/var/folders/tl/y1b6r4xj4sd3g3bh2hzk52r80000gn/T/pip-build-GZzOww/pypiwin32/
```

**Comment by pcinat** [comment]
Hi @stvhwrd ,
Thanks for reporting this.  As you can tell, my dev environment is on Windows :)

I'll start to take out the Win specific dependencies from the main requirements.txt and add additional OS specific files.

Also, the pypiwin32 library that you reference in the above is only needed for interacting with COM ports on the system.  This is what's used to send real-time data to Excel.  You can get around this issue by removing the dependency and still benefit from the many other features in this package.  I don't believe COM communications would work on non-Win systems anyways.

**Comment by pcinat** [comment]
Master branch updated to remove Windows libraries from the main requirements.txt file.  Added an optional requirements_win32.txt for users who want to install the Windows specific libraries.
